apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    node: details
  name: details
spec:
  selector:
    matchLabels:
      app: bookinfo
      node: details
  template:
    metadata:
      labels:
        app: bookinfo
        node: details
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        name: details
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    node: details
  name: details
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
  selector:
    app: bookinfo
    node: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    node: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      app: bookinfo
      node: mongodb
  template:
    metadata:
      labels:
        app: bookinfo
        node: mongodb
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-mongodb:1.16.2
        name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    node: mongodb
  name: mongodb
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    node: productpage
  name: productpage
spec:
  selector:
    matchLabels:
      app: bookinfo
      node: productpage
  template:
    metadata:
      labels:
        app: bookinfo
        node: productpage
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        name: productpage
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    node: productpage
  name: productpage
spec:
  ports:
  - name: http
    nodePort: 30000
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: bookinfo
    node: productpage
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    node: reviews
  name: reviews
spec:
  selector:
    matchLabels:
      app: bookinfo
      node: reviews
  template:
    metadata:
      labels:
        app: bookinfo
        node: reviews
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        name: reviews
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    node: reviews
  name: reviews
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: bookinfo
    node: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    node: ratings
  name: ratings
spec:
  selector:
    matchLabels:
      app: bookinfo
      node: ratings
  template:
    metadata:
      labels:
        app: bookinfo
        node: ratings
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-ratings-v2:1.16.2
        name: ratings
        env:
        - name: MONGO_DB_URL
          value: mongodb://mongodb:27017/test
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    node: ratings
  name: ratings
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: bookinfo
    node: ratings